blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/OrangeCat-Technologies/SyntX/discussions/categories/feature-requests
      about: Share and vote on feature requests for Syntx
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=OrangeCat-Technologies.syntx&ssr=false#review-details
      about: Enjoying Syntx? Leave a review here!
